### ISSUE TITLE
Eloquent ORM models ideal/preferred place

### ISSUE THREAD

**Issue by barnabas-szekeres** [beebmx/kirby-db#1]
Is there any ideal place for ORM models? The Kirby 3 basically place every page's model to `site/models` but what about the ORM models? Should be place to different place?

**Comment by beebmx** [comment]
For me the right place is `site/models` but, you can place it in any other location, just make sure than is visible for the project.

**Comment by barnabas-szekeres** [comment]
Thanks! :)
